//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenLDAP
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenLDAP.CorporateSoap")]
    public interface CorporateSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_GEN_DeleteAuthenLDAP", ReplyAction="*")]
        System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_DeleteAuthenLDAPResponse> WS_GEN_DeleteAuthenLDAPAsync(AuthenLDAP.WS_GEN_DeleteAuthenLDAPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_GEN_SearchAuthenLDAP", ReplyAction="*")]
        System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_SearchAuthenLDAPResponse> WS_GEN_SearchAuthenLDAPAsync(AuthenLDAP.WS_GEN_SearchAuthenLDAPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_GEN_ADDAuthenLDAP", ReplyAction="*")]
        System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_ADDAuthenLDAPResponse> WS_GEN_ADDAuthenLDAPAsync(AuthenLDAP.WS_GEN_ADDAuthenLDAPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_GEN_GetUserInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_GetUserInfoResponse> WS_GEN_GetUserInfoAsync(AuthenLDAP.WS_GEN_GetUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_GEN_AuthenLDAP", ReplyAction="*")]
        System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_AuthenLDAPResponse> WS_GEN_AuthenLDAPAsync(AuthenLDAP.WS_GEN_AuthenLDAPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WS_GEN_UpdateAuthenLDAP", ReplyAction="*")]
        System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_UpdateAuthenLDAPResponse> WS_GEN_UpdateAuthenLDAPAsync(AuthenLDAP.WS_GEN_UpdateAuthenLDAPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_GEN_DeleteAuthenLDAPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_GEN_DeleteAuthenLDAP", Namespace="http://tempuri.org/", Order=0)]
        public AuthenLDAP.WS_GEN_DeleteAuthenLDAPRequestBody Body;
        
        public WS_GEN_DeleteAuthenLDAPRequest()
        {
        }
        
        public WS_GEN_DeleteAuthenLDAPRequest(AuthenLDAP.WS_GEN_DeleteAuthenLDAPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WS_GEN_DeleteAuthenLDAPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string projectCode;
        
        public WS_GEN_DeleteAuthenLDAPRequestBody()
        {
        }
        
        public WS_GEN_DeleteAuthenLDAPRequestBody(string userName, string projectCode)
        {
            this.userName = userName;
            this.projectCode = projectCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_GEN_DeleteAuthenLDAPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_GEN_DeleteAuthenLDAPResponse", Namespace="http://tempuri.org/", Order=0)]
        public AuthenLDAP.WS_GEN_DeleteAuthenLDAPResponseBody Body;
        
        public WS_GEN_DeleteAuthenLDAPResponse()
        {
        }
        
        public WS_GEN_DeleteAuthenLDAPResponse(AuthenLDAP.WS_GEN_DeleteAuthenLDAPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WS_GEN_DeleteAuthenLDAPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement WS_GEN_DeleteAuthenLDAPResult;
        
        public WS_GEN_DeleteAuthenLDAPResponseBody()
        {
        }
        
        public WS_GEN_DeleteAuthenLDAPResponseBody(System.Xml.XmlElement WS_GEN_DeleteAuthenLDAPResult)
        {
            this.WS_GEN_DeleteAuthenLDAPResult = WS_GEN_DeleteAuthenLDAPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_GEN_SearchAuthenLDAPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_GEN_SearchAuthenLDAP", Namespace="http://tempuri.org/", Order=0)]
        public AuthenLDAP.WS_GEN_SearchAuthenLDAPRequestBody Body;
        
        public WS_GEN_SearchAuthenLDAPRequest()
        {
        }
        
        public WS_GEN_SearchAuthenLDAPRequest(AuthenLDAP.WS_GEN_SearchAuthenLDAPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WS_GEN_SearchAuthenLDAPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string projectCode;
        
        public WS_GEN_SearchAuthenLDAPRequestBody()
        {
        }
        
        public WS_GEN_SearchAuthenLDAPRequestBody(string userName, string passWd, string projectCode)
        {
            this.userName = userName;
            this.passWd = passWd;
            this.projectCode = projectCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_GEN_SearchAuthenLDAPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_GEN_SearchAuthenLDAPResponse", Namespace="http://tempuri.org/", Order=0)]
        public AuthenLDAP.WS_GEN_SearchAuthenLDAPResponseBody Body;
        
        public WS_GEN_SearchAuthenLDAPResponse()
        {
        }
        
        public WS_GEN_SearchAuthenLDAPResponse(AuthenLDAP.WS_GEN_SearchAuthenLDAPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WS_GEN_SearchAuthenLDAPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement WS_GEN_SearchAuthenLDAPResult;
        
        public WS_GEN_SearchAuthenLDAPResponseBody()
        {
        }
        
        public WS_GEN_SearchAuthenLDAPResponseBody(System.Xml.XmlElement WS_GEN_SearchAuthenLDAPResult)
        {
            this.WS_GEN_SearchAuthenLDAPResult = WS_GEN_SearchAuthenLDAPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_GEN_ADDAuthenLDAPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_GEN_ADDAuthenLDAP", Namespace="http://tempuri.org/", Order=0)]
        public AuthenLDAP.WS_GEN_ADDAuthenLDAPRequestBody Body;
        
        public WS_GEN_ADDAuthenLDAPRequest()
        {
        }
        
        public WS_GEN_ADDAuthenLDAPRequest(AuthenLDAP.WS_GEN_ADDAuthenLDAPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WS_GEN_ADDAuthenLDAPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string projectCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EECODE;
        
        public WS_GEN_ADDAuthenLDAPRequestBody()
        {
        }
        
        public WS_GEN_ADDAuthenLDAPRequestBody(string userName, string passWd, string projectCode, string EECODE)
        {
            this.userName = userName;
            this.passWd = passWd;
            this.projectCode = projectCode;
            this.EECODE = EECODE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_GEN_ADDAuthenLDAPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_GEN_ADDAuthenLDAPResponse", Namespace="http://tempuri.org/", Order=0)]
        public AuthenLDAP.WS_GEN_ADDAuthenLDAPResponseBody Body;
        
        public WS_GEN_ADDAuthenLDAPResponse()
        {
        }
        
        public WS_GEN_ADDAuthenLDAPResponse(AuthenLDAP.WS_GEN_ADDAuthenLDAPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WS_GEN_ADDAuthenLDAPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement WS_GEN_ADDAuthenLDAPResult;
        
        public WS_GEN_ADDAuthenLDAPResponseBody()
        {
        }
        
        public WS_GEN_ADDAuthenLDAPResponseBody(System.Xml.XmlElement WS_GEN_ADDAuthenLDAPResult)
        {
            this.WS_GEN_ADDAuthenLDAPResult = WS_GEN_ADDAuthenLDAPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_GEN_GetUserInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_GEN_GetUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public AuthenLDAP.WS_GEN_GetUserInfoRequestBody Body;
        
        public WS_GEN_GetUserInfoRequest()
        {
        }
        
        public WS_GEN_GetUserInfoRequest(AuthenLDAP.WS_GEN_GetUserInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WS_GEN_GetUserInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string projectCode;
        
        public WS_GEN_GetUserInfoRequestBody()
        {
        }
        
        public WS_GEN_GetUserInfoRequestBody(string userName, string projectCode)
        {
            this.userName = userName;
            this.projectCode = projectCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_GEN_GetUserInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_GEN_GetUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AuthenLDAP.WS_GEN_GetUserInfoResponseBody Body;
        
        public WS_GEN_GetUserInfoResponse()
        {
        }
        
        public WS_GEN_GetUserInfoResponse(AuthenLDAP.WS_GEN_GetUserInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WS_GEN_GetUserInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement WS_GEN_GetUserInfoResult;
        
        public WS_GEN_GetUserInfoResponseBody()
        {
        }
        
        public WS_GEN_GetUserInfoResponseBody(System.Xml.XmlElement WS_GEN_GetUserInfoResult)
        {
            this.WS_GEN_GetUserInfoResult = WS_GEN_GetUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_GEN_AuthenLDAPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_GEN_AuthenLDAP", Namespace="http://tempuri.org/", Order=0)]
        public AuthenLDAP.WS_GEN_AuthenLDAPRequestBody Body;
        
        public WS_GEN_AuthenLDAPRequest()
        {
        }
        
        public WS_GEN_AuthenLDAPRequest(AuthenLDAP.WS_GEN_AuthenLDAPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WS_GEN_AuthenLDAPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string projectCode;
        
        public WS_GEN_AuthenLDAPRequestBody()
        {
        }
        
        public WS_GEN_AuthenLDAPRequestBody(string userName, string passWd, string projectCode)
        {
            this.userName = userName;
            this.passWd = passWd;
            this.projectCode = projectCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_GEN_AuthenLDAPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_GEN_AuthenLDAPResponse", Namespace="http://tempuri.org/", Order=0)]
        public AuthenLDAP.WS_GEN_AuthenLDAPResponseBody Body;
        
        public WS_GEN_AuthenLDAPResponse()
        {
        }
        
        public WS_GEN_AuthenLDAPResponse(AuthenLDAP.WS_GEN_AuthenLDAPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WS_GEN_AuthenLDAPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement WS_GEN_AuthenLDAPResult;
        
        public WS_GEN_AuthenLDAPResponseBody()
        {
        }
        
        public WS_GEN_AuthenLDAPResponseBody(System.Xml.XmlElement WS_GEN_AuthenLDAPResult)
        {
            this.WS_GEN_AuthenLDAPResult = WS_GEN_AuthenLDAPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_GEN_UpdateAuthenLDAPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_GEN_UpdateAuthenLDAP", Namespace="http://tempuri.org/", Order=0)]
        public AuthenLDAP.WS_GEN_UpdateAuthenLDAPRequestBody Body;
        
        public WS_GEN_UpdateAuthenLDAPRequest()
        {
        }
        
        public WS_GEN_UpdateAuthenLDAPRequest(AuthenLDAP.WS_GEN_UpdateAuthenLDAPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WS_GEN_UpdateAuthenLDAPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OldPassWd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NewPassWd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string projectCode;
        
        public WS_GEN_UpdateAuthenLDAPRequestBody()
        {
        }
        
        public WS_GEN_UpdateAuthenLDAPRequestBody(string userName, string OldPassWd, string NewPassWd, string projectCode)
        {
            this.userName = userName;
            this.OldPassWd = OldPassWd;
            this.NewPassWd = NewPassWd;
            this.projectCode = projectCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WS_GEN_UpdateAuthenLDAPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WS_GEN_UpdateAuthenLDAPResponse", Namespace="http://tempuri.org/", Order=0)]
        public AuthenLDAP.WS_GEN_UpdateAuthenLDAPResponseBody Body;
        
        public WS_GEN_UpdateAuthenLDAPResponse()
        {
        }
        
        public WS_GEN_UpdateAuthenLDAPResponse(AuthenLDAP.WS_GEN_UpdateAuthenLDAPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WS_GEN_UpdateAuthenLDAPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement WS_GEN_UpdateAuthenLDAPResult;
        
        public WS_GEN_UpdateAuthenLDAPResponseBody()
        {
        }
        
        public WS_GEN_UpdateAuthenLDAPResponseBody(System.Xml.XmlElement WS_GEN_UpdateAuthenLDAPResult)
        {
            this.WS_GEN_UpdateAuthenLDAPResult = WS_GEN_UpdateAuthenLDAPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface CorporateSoapChannel : AuthenLDAP.CorporateSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class CorporateSoapClient : System.ServiceModel.ClientBase<AuthenLDAP.CorporateSoap>, AuthenLDAP.CorporateSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CorporateSoapClient() : 
                base(CorporateSoapClient.GetDefaultBinding(), CorporateSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CorporateSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CorporateSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CorporateSoapClient.GetBindingForEndpoint(endpointConfiguration), CorporateSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CorporateSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CorporateSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CorporateSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CorporateSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CorporateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_DeleteAuthenLDAPResponse> AuthenLDAP.CorporateSoap.WS_GEN_DeleteAuthenLDAPAsync(AuthenLDAP.WS_GEN_DeleteAuthenLDAPRequest request)
        {
            return base.Channel.WS_GEN_DeleteAuthenLDAPAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_DeleteAuthenLDAPResponse> WS_GEN_DeleteAuthenLDAPAsync(string userName, string projectCode)
        {
            AuthenLDAP.WS_GEN_DeleteAuthenLDAPRequest inValue = new AuthenLDAP.WS_GEN_DeleteAuthenLDAPRequest();
            inValue.Body = new AuthenLDAP.WS_GEN_DeleteAuthenLDAPRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.projectCode = projectCode;
            return ((AuthenLDAP.CorporateSoap)(this)).WS_GEN_DeleteAuthenLDAPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_SearchAuthenLDAPResponse> AuthenLDAP.CorporateSoap.WS_GEN_SearchAuthenLDAPAsync(AuthenLDAP.WS_GEN_SearchAuthenLDAPRequest request)
        {
            return base.Channel.WS_GEN_SearchAuthenLDAPAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_SearchAuthenLDAPResponse> WS_GEN_SearchAuthenLDAPAsync(string userName, string passWd, string projectCode)
        {
            AuthenLDAP.WS_GEN_SearchAuthenLDAPRequest inValue = new AuthenLDAP.WS_GEN_SearchAuthenLDAPRequest();
            inValue.Body = new AuthenLDAP.WS_GEN_SearchAuthenLDAPRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWd = passWd;
            inValue.Body.projectCode = projectCode;
            return ((AuthenLDAP.CorporateSoap)(this)).WS_GEN_SearchAuthenLDAPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_ADDAuthenLDAPResponse> AuthenLDAP.CorporateSoap.WS_GEN_ADDAuthenLDAPAsync(AuthenLDAP.WS_GEN_ADDAuthenLDAPRequest request)
        {
            return base.Channel.WS_GEN_ADDAuthenLDAPAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_ADDAuthenLDAPResponse> WS_GEN_ADDAuthenLDAPAsync(string userName, string passWd, string projectCode, string EECODE)
        {
            AuthenLDAP.WS_GEN_ADDAuthenLDAPRequest inValue = new AuthenLDAP.WS_GEN_ADDAuthenLDAPRequest();
            inValue.Body = new AuthenLDAP.WS_GEN_ADDAuthenLDAPRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWd = passWd;
            inValue.Body.projectCode = projectCode;
            inValue.Body.EECODE = EECODE;
            return ((AuthenLDAP.CorporateSoap)(this)).WS_GEN_ADDAuthenLDAPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_GetUserInfoResponse> AuthenLDAP.CorporateSoap.WS_GEN_GetUserInfoAsync(AuthenLDAP.WS_GEN_GetUserInfoRequest request)
        {
            return base.Channel.WS_GEN_GetUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_GetUserInfoResponse> WS_GEN_GetUserInfoAsync(string userName, string projectCode)
        {
            AuthenLDAP.WS_GEN_GetUserInfoRequest inValue = new AuthenLDAP.WS_GEN_GetUserInfoRequest();
            inValue.Body = new AuthenLDAP.WS_GEN_GetUserInfoRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.projectCode = projectCode;
            return ((AuthenLDAP.CorporateSoap)(this)).WS_GEN_GetUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_AuthenLDAPResponse> AuthenLDAP.CorporateSoap.WS_GEN_AuthenLDAPAsync(AuthenLDAP.WS_GEN_AuthenLDAPRequest request)
        {
            return base.Channel.WS_GEN_AuthenLDAPAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_AuthenLDAPResponse> WS_GEN_AuthenLDAPAsync(string userName, string passWd, string projectCode)
        {
            AuthenLDAP.WS_GEN_AuthenLDAPRequest inValue = new AuthenLDAP.WS_GEN_AuthenLDAPRequest();
            inValue.Body = new AuthenLDAP.WS_GEN_AuthenLDAPRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.passWd = passWd;
            inValue.Body.projectCode = projectCode;
            return ((AuthenLDAP.CorporateSoap)(this)).WS_GEN_AuthenLDAPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_UpdateAuthenLDAPResponse> AuthenLDAP.CorporateSoap.WS_GEN_UpdateAuthenLDAPAsync(AuthenLDAP.WS_GEN_UpdateAuthenLDAPRequest request)
        {
            return base.Channel.WS_GEN_UpdateAuthenLDAPAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenLDAP.WS_GEN_UpdateAuthenLDAPResponse> WS_GEN_UpdateAuthenLDAPAsync(string userName, string OldPassWd, string NewPassWd, string projectCode)
        {
            AuthenLDAP.WS_GEN_UpdateAuthenLDAPRequest inValue = new AuthenLDAP.WS_GEN_UpdateAuthenLDAPRequest();
            inValue.Body = new AuthenLDAP.WS_GEN_UpdateAuthenLDAPRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.OldPassWd = OldPassWd;
            inValue.Body.NewPassWd = NewPassWd;
            inValue.Body.projectCode = projectCode;
            return ((AuthenLDAP.CorporateSoap)(this)).WS_GEN_UpdateAuthenLDAPAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CorporateSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CorporateSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://dev-authenldapws.ais.co.th/corporate.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CorporateSoapClient.GetBindingForEndpoint(EndpointConfiguration.CorporateSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CorporateSoapClient.GetEndpointAddress(EndpointConfiguration.CorporateSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            CorporateSoap,
        }
    }
}
